apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api
  namespace: dev
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-api

  template:
    metadata:
      labels:
        app: ai-api

    spec:
      containers:
        - name: ai-api
          image: 810967692205.dkr.ecr.ap-southeast-1.amazonaws.com/dev-ai-api:bb058f3c37020e861705ad35efb8f15838cd9843

          ports:
            - containerPort: 8000